const resources: Record<string, string> = {
  accounts:'Tài khoản',users:'Hồ sơ người dùng',companyprofiles:'Hồ sơ doanh nghiệp',usersettings:'Cài đặt người dùng',userpresences:'Trạng thái trực tuyến',professions:'Ngành nghề',userprofessions:'Ngành nghề người dùng',skills:'Kỹ năng',userskills:'Kỹ năng người dùng',socialplatforms:'Nền tảng mạng xã hội',usersocialaccounts:'Mạng xã hội người dùng',userfollows:'Lượt theo dõi',userblocks:'Danh sách chặn',searchhistory:'Lịch sử tìm kiếm',services:'Dịch vụ',servicemedia:'Ảnh và video dịch vụ',portfolioprojects:'Portfolio',portfoliomedia:'Ảnh và video portfolio',portfoliolikes:'Lượt thích portfolio',portfolioviews:'Lượt xem portfolio',inspirationcategories:'Danh mục cảm hứng',inspirationposts:'Bài đăng cảm hứng',inspirationlikes:'Lượt thích cảm hứng',inspirationsaves:'Lượt lưu cảm hứng',inspirationviews:'Lượt xem cảm hứng',fileassets:'Tệp đã tải lên',projects:'Dự án',projectapplications:'Ứng tuyển dự án',projectproposals:'Đề xuất dự án',projectassignments:'Phân công dự án',projectmilestones:'Mốc dự án',projectdeliverables:'Sản phẩm bàn giao',projectdeliverableassets:'Tệp bàn giao dự án',serviceorders:'Đơn dịch vụ',serviceorderpayments:'Thanh toán đơn dịch vụ',serviceorderdeliverables:'Bàn giao đơn dịch vụ',serviceorderdeliverableassets:'Tệp bàn giao dịch vụ',wallets:'Ví',wallettransactions:'Giao dịch ví',walletbankaccounts:'Tài khoản ngân hàng',depositrequests:'Yêu cầu nạp tiền',withdrawalrequests:'Yêu cầu rút tiền',projectpayments:'Thanh toán dự án',disputes:'Tranh chấp',disputeevidence:'Bằng chứng tranh chấp',conversations:'Phòng trò chuyện',conversationmembers:'Thành viên phòng',messages:'Tin nhắn',messageattachments:'Tệp đính kèm tin nhắn',messagereferences:'Nội dung liên kết',reviews:'Đánh giá',notifications:'Thông báo',reports:'Báo cáo',campaigns:'Chiến dịch',campaignparticipants:'Người tham gia chiến dịch',auditlogs:'Nhật ký quản trị'
};
const fields: Record<string, string> = {
  Id:'Mã',AccountId:'Mã tài khoản',UserId:'Mã người dùng',DisplayName:'Tên hiển thị',FullName:'Họ và tên',Email:'Email',Phone:'Số điện thoại',Role:'Vai trò',Status:'Trạng thái',JobTitle:'Chức vụ',AvatarUrl:'Ảnh đại diện',CoverUrl:'Ảnh bìa',Bio:'Giới thiệu',Province:'Tỉnh/thành',Country:'Quốc gia',Title:'Tiêu đề',Name:'Tên',Description:'Mô tả',Content:'Nội dung',CreatedAt:'Ngày tạo',UpdatedAt:'Ngày cập nhật',DeletedAt:'Ngày xóa',LastLoginAt:'Đăng nhập gần nhất',IsVerified:'Đã xác minh',IsAvailableForWork:'Sẵn sàng làm việc',ProjectId:'Mã dự án',ServiceId:'Mã dịch vụ',ServiceOrderId:'Mã đơn dịch vụ',ConversationId:'Mã phòng',SenderId:'Người gửi',ClientId:'Khách hàng',CreativeId:'Người sáng tạo',OwnerUserId:'Chủ sở hữu',JoinedAt:'Thời gian tham gia',LastMessageAt:'Tin nhắn gần nhất',MessageType:'Loại tin nhắn',Budget:'Ngân sách',TotalAmount:'Tổng tiền',Amount:'Số tiền',Currency:'Tiền tệ',Rating:'Điểm đánh giá',Requirements:'Yêu cầu',Deadline:'Hạn chót',Location:'Địa điểm',IsRemote:'Làm việc từ xa',AvailableBalance:'Số dư khả dụng',LockedBalance:'Số dư tạm giữ',Type:'Loại',Action:'Hành động',CallToAction:'Nội dung nút kêu gọi',StartsAt:'Ngày bắt đầu',EndsAt:'Ngày kết thúc',TargetUrl:'Đường dẫn khi bấm nút',IsFeatured:'Hiển thị nổi bật'
};
const hints: Record<string,string> = {CallToAction:'Chữ hiển thị trên nút, ví dụ: Tham gia ngay.',StartsAt:'Có thể nhập ngày giờ trực tiếp hoặc chọn từ lịch.',EndsAt:'Thời điểm chiến dịch ngừng hiển thị; có thể nhập hoặc chọn từ lịch.',TargetUrl:'Trang sẽ mở khi người dùng bấm nút kêu gọi.',IsFeatured:'Ưu tiên chiến dịch ở vị trí nổi bật trên ứng dụng.',Status:'Bản nháp chưa hiển thị; Đang hoạt động sẽ hiển thị theo thời gian đã chọn.'};
const values: Record<string, string> = { Active:'Đang hoạt động',Inactive:'Ngừng hoạt động',Pending:'Đang chờ',Approved:'Đã duyệt',Rejected:'Đã từ chối',Completed:'Đã hoàn thành',Cancelled:'Đã hủy',Deleted:'Đã xóa',Draft:'Bản nháp',Published:'Đã đăng',Open:'Đang mở',Closed:'Đã đóng',Processing:'Đang xử lý',Failed:'Thất bại',Success:'Thành công',Admin:'Quản trị viên',Client:'Khách hàng',Creative:'Người sáng tạo',Member:'Thành viên',Owner:'Chủ phòng',Private:'Riêng tư',Group:'Nhóm',Text:'Văn bản',Image:'Hình ảnh',Video:'Video' };
export const primaryResources = new Set(['accounts','services','portfolioprojects','inspirationposts','projects','serviceorders','conversations','reviews','reports','wallets','withdrawalrequests','disputes','campaigns','auditlogs']);
export function resourceLabel(key:string,fallback?:string){return resources[key.toLowerCase()]||fallback||key;}
export function fieldLabel(name:string){return fields[name]||name.replace(/Id$/,' (mã)');}
export function fieldHint(name:string){return hints[name]||'';}
export function valueLabel(value:unknown){return typeof value==='string'?values[value]||value:value;}
