import { useState,type FormEvent } from 'react';
import type { AdminResource } from '../types/admin.types';
import { fieldLabel,valueLabel } from '../config/admin-i18n';

export function RecordEditor({resource,data,busy,onSave,onCancel}:{resource:AdminResource;data:Record<string,unknown>;busy:boolean;onSave:(values:Record<string,unknown>)=>Promise<void>;onCancel:()=>void}){
 const fields=resource.fields.filter(x=>x.editable); const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(x=>[x.name,data[x.name]==null?'':String(data[x.name])])));
 async function submit(event:FormEvent){event.preventDefault();const changed:Record<string,unknown>={};fields.forEach(field=>{if(values[field.name]!==String(data[field.name]??''))changed[field.name]=parseValue(field.type,values[field.name],field.nullable);});await onSave(changed);}
 return <form className="editor" onSubmit={submit}>{fields.map(field=><label key={field.name}><span>{fieldLabel(field.name)}{!field.nullable&&' *'}</span>{field.options?<select value={values[field.name]} onChange={e=>setValues(v=>({...v,[field.name]:e.target.value}))}>{field.nullable&&<option value="">—</option>}{field.options.filter(x=>x!=='Deleted').map(x=><option key={x} value={x}>{String(valueLabel(x))}</option>)}</select>:field.type==='Boolean'?<select value={values[field.name]} onChange={e=>setValues(v=>({...v,[field.name]:e.target.value}))}><option value="true">Có</option><option value="false">Không</option></select>:<input value={values[field.name]} maxLength={field.maxLength||undefined} type={field.type==='DateTimeOffset'?'datetime-local':['Int16','Int32','Int64','Decimal'].includes(field.type)?'number':'text'} onChange={e=>setValues(v=>({...v,[field.name]:e.target.value}))}/>}</label>)}<div className="editor-actions"><button type="button" className="quiet" onClick={onCancel}>Hủy</button><button disabled={busy||fields.length===0}>{busy?'Đang lưu…':'Lưu thay đổi'}</button></div></form>;
}
function parseValue(type:string,value:string,nullable:boolean){if(value===''&&nullable)return null;if(type==='Boolean')return value==='true';if(['Int16','Int32','Int64','Decimal'].includes(type))return Number(value);return value;}
