import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { AdminDataTable, AdminPageHeader, AdminPagination, StatusBadge, type AdminColumn } from '../../components/admin/AdminUi';
import { ErrorState, LoadingState } from '../../components/AsyncState';
import { adminService } from '../../services/admin.service';
import type { AdminProjectListItem, AdminServiceListItem, AdminWorkOrderListItem, OperationFilters, OperationPage } from '../../types/admin.types';
import { formatAdminDateTime, formatAdminId, formatAdminMoney } from '../../utils/admin-presentation';

type Kind='projects'|'services'|'work-orders';
type Row={id:string;primary:string;secondary:string;context:string;amount:number|null;status:string;metric:string;createdAt:string};
const configs={projects:{eyebrow:'Marketplace / Nhu cầu',title:'Dự án',description:'Theo dõi nhu cầu tuyển Creative, ngân sách, hồ sơ ứng tuyển và tiến độ.',placeholder:'Tên dự án, client hoặc email…',statuses:['OPEN','IN_PROGRESS','AWAITING_COMPLETION','COMPLETED','CANCELLED','DRAFT']},services:{eyebrow:'Marketplace / Nguồn cung',title:'Dịch vụ',description:'Quản lý dịch vụ đang niêm yết, Creative, giá, đơn hàng và chất lượng.',placeholder:'Tên dịch vụ, Creative hoặc email…',statuses:['ACTIVE','DRAFT','HIDDEN','DELETED']},'work-orders':{eyebrow:'Vận hành / Giao việc',title:'Work Orders',description:'Theo dõi luồng giao việc thống nhất, hai bên, deadline và trạng thái bàn giao.',placeholder:'Tên công việc, người mua hoặc Creative…',statuses:['PENDING_PAYMENT','IN_PROGRESS','SUBMITTED','REVISION_REQUESTED','OVERDUE','DISPUTED','COMPLETED','CANCELLED']}} as const;

export function MarketplaceListPage({kind}:{kind:Kind}) {
  const config=configs[kind];const [params,setParams]=useSearchParams();const filters=readFilters(params);const [draft,setDraft]=useState(filters.search??'');const [data,setData]=useState<OperationPage<Row>>();const [error,setError]=useState('');
  useEffect(()=>{setData(undefined);setError('');load(kind,filters).then(page=>setData({...page,items:page.items.map(item=>normalize(kind,item))})).catch(cause=>setError(cause.message));},[kind,params.toString()]);
  const columns=useMemo<AdminColumn<Row>[]>(()=>[{key:'primary',label:kind==='work-orders'?'Công việc':config.title,render:item=><div className="ops-primary-cell"><strong>{item.primary}</strong><small>{item.secondary}</small></div>},{key:'context',label:kind==='services'?'Nghề nghiệp':'Ngữ cảnh',render:item=>item.context},{key:'amount',label:kind==='services'?'Giá':'Giá trị',render:item=>formatAdminMoney(item.amount)},{key:'metric',label:kind==='projects'?'Ứng tuyển':kind==='services'?'Hiệu suất':'Deadline',render:item=>item.metric},{key:'status',label:'Trạng thái',render:item=><StatusBadge status={item.status}/>},{key:'created',label:'Ngày tạo',render:item=>formatAdminDateTime(item.createdAt)},{key:'id',label:'Mã',render:item=><code>{formatAdminId(item.id)}</code>}],[kind,config.title]);
  const update=(key:string,value:string|number|undefined)=>setParams(current=>{const next=new URLSearchParams(current);if(value===undefined||value==='')next.delete(key);else next.set(key,String(value));if(key!=='page')next.set('page','1');return next;});const submit=(event:FormEvent)=>{event.preventDefault();update('search',draft.trim()||undefined);};
  if(error)return <ErrorState message={error} retry={()=>setParams(new URLSearchParams(params))}/>;
  return <div className="ops-list-page"><AdminPageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} status={<StatusBadge label={`${(data?.total??0).toLocaleString('vi-VN')} hồ sơ`} tone="neutral"/>}/><form className="ops-filter-bar ops-filter-bar--compact" onSubmit={submit}><label className="ops-search-field"><span>Tìm kiếm</span><input type="search" value={draft} onChange={event=>setDraft(event.target.value)} placeholder={config.placeholder}/></label><label><span>Trạng thái</span><select value={filters.status??''} onChange={event=>update('status',event.target.value||undefined)}><option value="">Tất cả</option>{config.statuses.map(status=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select></label><button type="submit">Áp dụng</button><button className="ops-button-ghost" type="button" onClick={()=>{setDraft('');setParams({});}}>Xóa lọc</button></form>{!data?<LoadingState/>:<><AdminDataTable columns={columns} items={data.items} rowLink={item=>detailPath(kind,item.id)} emptyTitle={`Không tìm thấy ${config.title.toLocaleLowerCase('vi')}`} emptyMessage="Thử thay đổi từ khóa hoặc trạng thái."/><AdminPagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={page=>update('page',page)}/></>}</div>;
}
function readFilters(params:URLSearchParams):OperationFilters{return{page:Math.max(1,Number(params.get('page'))||1),pageSize:20,search:params.get('search')||undefined,status:params.get('status')||undefined};}
function load(kind:Kind,filters:OperationFilters){if(kind==='projects')return adminService.projects(filters);if(kind==='services')return adminService.services(filters);return adminService.workOrders(filters);}
function normalize(kind:Kind,item:AdminProjectListItem|AdminServiceListItem|AdminWorkOrderListItem):Row{if(kind==='projects'){const x=item as AdminProjectListItem;return{id:x.id,primary:x.title,secondary:`${x.clientName} · ${x.clientEmail}`,context:x.profession,amount:x.budget,status:x.status,metric:`${x.applicationCount} hồ sơ`,createdAt:x.createdAt};}if(kind==='services'){const x=item as AdminServiceListItem;return{id:x.id,primary:x.title,secondary:`${x.creativeName} · ${x.creativeEmail}`,context:x.profession,amount:x.price,status:x.status,metric:`${x.orderCount} đơn · ${x.averageRating??'—'} ★`,createdAt:x.createdAt};}const x=item as AdminWorkOrderListItem;return{id:x.id,primary:x.title,secondary:`${x.buyerName} → ${x.creativeName}`,context:x.source,amount:x.agreedPrice,status:x.status,metric:formatAdminDateTime(x.deadline),createdAt:x.createdAt};}
function detailPath(kind:Kind,id:string){return kind==='projects'?`/resources/projects/${id}`:kind==='services'?`/resources/services/${id}`:`/resources/workorders/${id}`;}
