import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ErrorState, LoadingState } from '../../components/AsyncState';
import { adminService } from '../../services/admin.service';
import type { WithdrawalDetail } from '../../types/admin.types';
import { formatAdminDate, formatVnd } from './withdrawal-format';
import { withdrawalAuditLabel, withdrawalStatusLabel, withdrawalStatusTone } from './withdrawal-status';

type Dialog = 'start'|'reject'|'fail'|'complete'|null;

export function WithdrawalDetailPage(){
  const {id=''}=useParams();const[data,setData]=useState<WithdrawalDetail>();const[error,setError]=useState('');const[toast,setToast]=useState('');const[busy,setBusy]=useState(false);const[dialog,setDialog]=useState<Dialog>(null);const[reason,setReason]=useState('');const[bankReference,setBankReference]=useState('');const[adminNote,setAdminNote]=useState('');const[fundsMayHaveTransferred,setFundsMayHaveTransferred]=useState(false);
  const load=()=>{setError('');adminService.withdrawal(id).then(setData).catch(reason=>setError(reason.message))};useEffect(load,[id]);
  const act=async(work:()=>Promise<WithdrawalDetail>,message:string)=>{setBusy(true);setError('');try{setData(await work());setToast(message);setDialog(null);setReason('')}catch(reason){setError(reason instanceof Error?reason.message:'Không thể thực hiện thao tác.')}finally{setBusy(false)}};
  const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);setToast(`Đã sao chép ${label}.`)}catch{setError(`Không thể sao chép ${label}.`)}};
  const upload=async(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','application/pdf'].includes(file.type)||file.size>8*1024*1024){setError('Biên lai chỉ hỗ trợ JPG, PNG hoặc PDF tối đa 8 MB.');return}await act(()=>adminService.uploadWithdrawalReceipt(id,file),'Đã tải biên lai.')};
  if(error&&!data)return <ErrorState message={error} retry={load}/>;if(!data)return <LoadingState/>;
  return <div className="withdrawal-detail"><div className="detail-back"><Link to="/admin/withdrawals">← Yêu cầu rút tiền</Link></div><header className="withdrawal-detail-head"><div><span className="eyebrow">Yêu cầu rút tiền</span><h1>{data.withdrawalCode}</h1><p>{data.creativeName} · {data.email} · {formatAdminDate(data.requestedAt)}</p></div><span className={`withdrawal-badge large ${withdrawalStatusTone[data.status]}`}>{withdrawalStatusLabel[data.status]}</span></header>
    {toast?<div className="withdrawal-toast" role="status">{toast}<button onClick={()=>setToast('')}>×</button></div>:null}{error?<div className="withdrawal-toast error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>:null}{data.requiresManualReview?<div className="manual-review-warning"><strong>Cần đối soát thủ công</strong><span>Không hoàn tiền tự động vì giao dịch có thể đã rời tài khoản ngân hàng công ty.</span></div>:null}
    <section className="withdrawal-amounts"><Metric label="Số tiền yêu cầu" value={formatVnd(data.amount)}/><Metric label="Phí" value={formatVnd(data.fee)}/><Metric emphasis label="Thực nhận" value={formatVnd(data.netAmount)}/></section>
    <div className="withdrawal-detail-grid"><section className="withdrawal-panel"><PanelTitle title="Người yêu cầu"/><Info label="Creative" value={data.creativeName}/><Info label="Email" value={data.email}/><Info label="Thời gian" value={formatAdminDate(data.requestedAt)}/><Info label="Người xử lý" value={data.processor??'Chưa tiếp nhận'}/></section><section className="withdrawal-panel"><PanelTitle title="Tài khoản nhận"/><Info label="Ngân hàng" value={`${data.bankName} (${data.bankCode})`}/><Info action={()=>void copy(data.bankAccountNumber,'số tài khoản')} actionLabel="Copy STK" label="Số tài khoản" value={data.bankAccountNumber}/><Info label="Chủ tài khoản" value={data.bankAccountName}/></section></div>
    {data.status==='PENDING'?<section className="withdrawal-actions"><button className="danger-outline" onClick={()=>setDialog('reject')}>Từ chối</button><button className="primary-action" onClick={()=>setDialog('start')}>Bắt đầu xử lý</button></section>:null}
    {data.status==='PROCESSING'?<Processing data={data} bankReference={bankReference} adminNote={adminNote} busy={busy} onBankReference={setBankReference} onNote={setAdminNote} onCopy={copy} onComplete={()=>{if(bankReference.trim().length<3){setError('Vui lòng nhập mã giao dịch ngân hàng.');return}setDialog('complete')}} onFail={()=>setDialog('fail')} onUpload={upload}/>:null}
    {data.receiptUrl?<section className="withdrawal-panel receipt-panel"><PanelTitle title="Biên lai chuyển khoản"/><a href={data.receiptUrl} target="_blank" rel="noreferrer">Xem biên lai đã tải ↗</a></section>:null}
    <section className="withdrawal-panel timeline"><PanelTitle title="Lịch sử"/>{data.timeline.length?data.timeline.map((item,index)=><div className="timeline-row" key={`${item.createdAt}-${index}`}><time>{formatAdminDate(item.createdAt)}</time><span/><div><strong>{withdrawalAuditLabel[item.action]??item.action}</strong><small>{item.actor}</small></div></div>):<p className="timeline-empty">Chưa có lịch sử thao tác.</p>}</section>
    {dialog?<Confirmation dialog={dialog} data={data} reason={reason} fundsMayHaveTransferred={fundsMayHaveTransferred} busy={busy} bankReference={bankReference} onReason={setReason} onFunds={setFundsMayHaveTransferred} onClose={()=>setDialog(null)} onConfirm={()=>{if(dialog==='start')void act(()=>adminService.startWithdrawal(id),'Đã tiếp nhận xử lý yêu cầu.');if(dialog==='reject')void act(()=>adminService.rejectWithdrawal(id,reason),'Đã từ chối và hoàn tiền về ví.');if(dialog==='fail')void act(()=>adminService.failWithdrawal(id,reason,fundsMayHaveTransferred),'Đã ghi nhận xử lý thất bại.');if(dialog==='complete')void act(()=>adminService.completeWithdrawal(id,bankReference,adminNote),'Đã xác nhận chuyển tiền thành công.')}}/>:null}
  </div>
}

function Processing({data,bankReference,adminNote,busy,onBankReference,onNote,onCopy,onComplete,onFail,onUpload}:{data:WithdrawalDetail;bankReference:string;adminNote:string;busy:boolean;onBankReference(v:string):void;onNote(v:string):void;onCopy(v:string,l:string):Promise<void>;onComplete():void;onFail():void;onUpload(file?:File):Promise<void>}){return <div className="processing-grid"><section className="vietqr-card"><span className="eyebrow">Quét để chuyển</span><img alt={`VietQR ${data.withdrawalCode}`} src={data.qrCodeUrl}/><strong>{formatVnd(data.netAmount)}</strong><p>{data.bankName}<br/>{data.bankAccountNumber}<br/>{data.bankAccountName}</p><div><span>Nội dung</span><code>{data.transferContent}</code><button onClick={()=>void onCopy(data.transferContent,'nội dung')}>Copy nội dung</button></div><aside>Vui lòng kiểm tra tên người nhận, số tài khoản và số tiền trên ứng dụng ngân hàng trước khi xác nhận chuyển khoản.</aside></section><section className="transfer-form"><span className="eyebrow">Xác nhận chuyển khoản</span><h2>Thông tin đối soát</h2><label><span>Mã giao dịch ngân hàng *</span><input placeholder="FTXXXXXXXX" value={bankReference} onChange={event=>onBankReference(event.target.value)}/></label><label><span>Biên lai</span><input accept="image/jpeg,image/png,application/pdf" disabled={busy} type="file" onChange={event=>void onUpload(event.target.files?.[0])}/><small>JPG, PNG hoặc PDF · tối đa 8 MB</small></label><label><span>Ghi chú</span><textarea maxLength={2000} value={adminNote} onChange={event=>onNote(event.target.value)}/></label><div className="transfer-actions"><button className="danger-outline" onClick={onFail}>Đánh dấu thất bại</button><button className="primary-action" disabled={busy} onClick={onComplete}>Xác nhận đã chuyển tiền</button></div></section></div>}
function Confirmation({dialog,data,reason,fundsMayHaveTransferred,busy,bankReference,onReason,onFunds,onClose,onConfirm}:{dialog:Exclude<Dialog,null>;data:WithdrawalDetail;reason:string;fundsMayHaveTransferred:boolean;busy:boolean;bankReference:string;onReason(v:string):void;onFunds(v:boolean):void;onClose():void;onConfirm():void}){const reasonDialog=dialog==='reject'||dialog==='fail';return <div className="withdrawal-modal" role="dialog" aria-modal="true"><section><span className="eyebrow">{dialog==='complete'?'XÁC NHẬN CHUYỂN TIỀN':'Xác nhận thao tác'}</span><h2>{dialog==='start'?'Bắt đầu xử lý yêu cầu?':dialog==='reject'?'Từ chối yêu cầu?':dialog==='fail'?'Đánh dấu xử lý thất bại?':'Xác nhận đã chuyển tiền?'}</h2><div className="confirm-summary"><strong>{formatVnd(data.netAmount)}</strong><span>{data.withdrawalCode}</span><span>{data.creativeName}</span>{dialog==='complete'?<><span>{data.bankName} · {data.bankAccountNumber}</span><span>Mã giao dịch: {bankReference}</span></>:null}</div>{reasonDialog?<label><span>{dialog==='reject'?'Lý do từ chối *':'Lý do thất bại *'}</span><textarea autoFocus maxLength={2000} value={reason} onChange={event=>onReason(event.target.value)}/></label>:null}{dialog==='fail'?<label className="review-checkbox"><input checked={fundsMayHaveTransferred} type="checkbox" onChange={event=>onFunds(event.target.checked)}/><span>Tiền có thể đã rời tài khoản ngân hàng — giữ hold và yêu cầu đối soát thủ công</span></label>:null}<p>{dialog==='complete'?'Sau khi xác nhận, yêu cầu sẽ được đánh dấu hoàn thành.':dialog==='reject'?'Số tiền hold sẽ được hoàn lại vào số dư khả dụng.':null}</p><div className="modal-actions"><button onClick={onClose}>Quay lại</button><button className={dialog==='reject'||dialog==='fail'?'danger-action':'primary-action'} disabled={busy||(reasonDialog&&reason.trim().length<3)} onClick={onConfirm}>{busy?'Đang xử lý…':dialog==='complete'?'Xác nhận đã chuyển':'Xác nhận'}</button></div></section></div>}
function Metric({label,value,emphasis}:{label:string;value:string;emphasis?:boolean}){return <article className={emphasis?'emphasis':''}><span>{label}</span><strong>{value}</strong></article>}
function PanelTitle({title}:{title:string}){return <header><h2>{title}</h2></header>}
function Info({label,value,action,actionLabel}:{label:string;value:string;action?:()=>void;actionLabel?:string}){return <div className="withdrawal-info"><span>{label}</span><strong>{value}</strong>{action?<button onClick={action}>{actionLabel}</button>:null}</div>}
